version: "3.9"

services:
  server:
    build: .
    command: >
      bash -c "
        yes | python manage.py makemigrations Auth post application chat &&
        python manage.py migrate --noinput &&
        python manage.py create_superuser_if_not_exists &&
        yes | python manage.py search_index --rebuild &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      postgresql:
        condition: service_started
    volumes:
      - .:/app

  asgi:
    build: .
    command: bash -c "uvicorn ProjectCore.asgi:application --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
    command: celery -A ProjectCore worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
